Stop using the host's cgroupfs on Kubernetes server
Using a hostPath for the server cgroupfs can lead to the corruption of
the cgroupfs on the host. Using an empty folder and mounting the
cgroupfs in it is safer, but requires additional tricks for systemd to
properly start on an selinux enforced node.

An example of corrupted host cgroups is that kubectl exec in the
container can give this kind of error:

error: Internal error occurred: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "3857f8f65cc712e8a9854095647342e43994023bbd16c0f894c636890e025af6": OCI runtime exec failed: exec failed: unable to start container process: error starting setns process: can't open cgroup: openat2 /sys/fs/cgroup/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod977787e4_c006_4029_a273_7d206f9087aa.slice/cri-containerd-a1a7f34705140485ea47227ad0624fb284efd37a6db80fe9edeebde846ac97c8.scope: no such file or directory